[package]
name = "erc5006_cairo"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"
openzeppelin_introspection = "0.17.0"
openzeppelin_token = "0.17.0"

[dev-dependencies]
assert_macros = "2.8.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"