[package]
name = "erc_7662_ai_agent_nft"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag="v0.17.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true

[scripts]
test = "snforge test"
